server:
  port: 8080

spring:
  application:
    name: firefly-auth
  profiles:
    active: dev
  config:
    import: optional:nacos:${spring.application.name}.${spring.profiles.active}.yaml
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
        import-check:
          enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firefly?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: firefly
    password: Hello@1234
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.firefly.auth.repository.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

# 雪花算法配置
snowflake:
  datacenter-id: 1  # 数据中心ID
  machine-id: 1     # 机器ID

jwt:
  secret: "firefly-auth-secret-key-2024-01-01-abcdefghijklmnopqrstuvwxyz"  # 建议在生产环境中使用更安全的密钥
  expiration: 86400000  # 24小时，单位毫秒 